WIP

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -211,73 +211,67 @@ jobs:
         run: |
           echo '${{ github.workspace }}'"/external/dlls-${{ matrix.target.cpu }}" >> $GITHUB_PATH
 
-      - name: Get latest nimbus-build-system commit hash
-        id: versions
-        run: |
-          getHash() {
-            git ls-remote "https://github.com/$1" "${2:-HEAD}" | cut -f 1
-          }
-          nbsHash=$(getHash status-im/nimbus-build-system)
-          echo "nimbus_build_system=$nbsHash" >> $GITHUB_OUTPUT
+      - name: Setup Nimble
+        uses: nim-lang/nimble/.github/actions/install_nimble@master
+        with:
+          os: ${{ matrix.target.os }}
+          cpu: ${{ matrix.target.cpu }}
 
-      - name: Restore prebuilt Nim from cache
-        id: nim-cache
+      - name: Restore nimble dependencies from cache
+        id: nimble_deps
         uses: actions/cache@v3
         with:
-          path: NimBinCache
-          key: 'nim-${{ matrix.target.os }}-${{ matrix.target.cpu }}-${{ steps.versions.outputs.nimbus_build_system }}'
+          path: ~/.nimble/
+          key: ${{ matrix.target.os }}-${{ env.cache_nonce }}
 
-      - name: Build Nim and Nimbus-eth1 dependencies
-        run: |
-          make -j${ncpu} ARCH_OVERRIDE=${PLATFORM} CI_CACHE=NimBinCache update
+      - name: Install deps
+        run: nimble -y build
 
-      - name: Run nimbus-eth1 tests (Windows)
-        if: runner.os == 'Windows'
-        run: |
-          gcc --version
-          DEFAULT_MAKE_FLAGS="-j${ncpu} ENABLE_EVMC=${ENABLE_EVMC} ENABLE_VMLOWMEM=${ENABLE_VMLOWMEM}"
-          mingw32-make ${DEFAULT_MAKE_FLAGS}
-          build/nimbus.exe --help
-          # give us more space
-          find . -type d -name ".git" -exec rm -rf {} +
-          find . -type d -name "nimcache" -exec rm -rf {} +
-          mingw32-make ${DEFAULT_MAKE_FLAGS} test
-          if [[ '${{ matrix.target.cpu }}' == 'amd64' ]]; then
-            mingw32-make ${DEFAULT_MAKE_FLAGS}
-          fi
+      # - name: Run nimbus-eth1 tests (Windows)
+      #   if: runner.os == 'Windows'
+      #   run: |
+      #     gcc --version
+      #     DEFAULT_MAKE_FLAGS="-j${ncpu} ENABLE_EVMC=${ENABLE_EVMC} ENABLE_VMLOWMEM=${ENABLE_VMLOWMEM}"
+      #     mingw32-make ${DEFAULT_MAKE_FLAGS}
+      #     build/nimbus.exe --help
+      #     # give us more space
+      #     find . -type d -name ".git" -exec rm -rf {} +
+      #     find . -type d -name "nimcache" -exec rm -rf {} +
+      #     mingw32-make ${DEFAULT_MAKE_FLAGS} test
+      #     if [[ '${{ matrix.target.cpu }}' == 'amd64' ]]; then
+      #       mingw32-make ${DEFAULT_MAKE_FLAGS}
+      #     fi
 
-      - name: Run nimbus-eth1 tests (Linux)
-        if: runner.os == 'Linux'
-        run: |
-          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"
-          DEFAULT_MAKE_FLAGS="-j${ncpu} USE_MIRACL=${USE_MIRACL} ENABLE_EVMC=${ENABLE_EVMC}"
-          env CC=gcc make ${DEFAULT_MAKE_FLAGS}
-          build/nimbus --help
-          # CC, GOARCH, and CGO_ENABLED are needed to select correct compiler 32/64 bit
-          if [[ '${{ matrix.target.cpu }}' == 'i386' ]]; then
-            # hide CI failures
-            env CC=gcc GOARCH=${GOARCH} CXX=g++ CGO_ENABLED=1 make ${DEFAULT_MAKE_FLAGS} test || true
-          else
-            # pushd vendor/nimbus-eth2
-            # env NIMBUSEL_BINARY=../../build/nimbus NIMBUSEL_GENESIS=scripts/nimbusel_genesis.json \
-            # ./scripts/launch_local_testnet.sh --nodes=3 --stop-at-epoch=7 \
-            # --disable-htop --reuse-binaries --run-nimbus-el --dl-eth2 --verbose --kill-old-processes
-            # popd
-            env CC=gcc GOARCH=${GOARCH} CXX=g++ CGO_ENABLED=1 make ${DEFAULT_MAKE_FLAGS} test
-          fi
+      # - name: Run nimbus-eth1 tests (Linux)
+      #   if: runner.os == 'Linux'
+      #   run: |
+      #     export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"
+      #     DEFAULT_MAKE_FLAGS="-j${ncpu} USE_MIRACL=${USE_MIRACL} ENABLE_EVMC=${ENABLE_EVMC}"
+      #     env CC=gcc make ${DEFAULT_MAKE_FLAGS}
+      #     build/nimbus --help
+      #     # CC, GOARCH, and CGO_ENABLED are needed to select correct compiler 32/64 bit
+      #     if [[ '${{ matrix.target.cpu }}' == 'i386' ]]; then
+      #       # hide CI failures
+      #       env CC=gcc GOARCH=${GOARCH} CXX=g++ CGO_ENABLED=1 make ${DEFAULT_MAKE_FLAGS} test || true
+      #     else
+      #       # pushd vendor/nimbus-eth2
+      #       # env NIMBUSEL_BINARY=../../build/nimbus NIMBUSEL_GENESIS=scripts/nimbusel_genesis.json \
+      #       # ./scripts/launch_local_testnet.sh --nodes=3 --stop-at-epoch=7 \
+      #       # --disable-htop --reuse-binaries --run-nimbus-el --dl-eth2 --verbose --kill-old-processes
+      #       # popd
+      #       env CC=gcc GOARCH=${GOARCH} CXX=g++ CGO_ENABLED=1 make ${DEFAULT_MAKE_FLAGS} test
+      #     fi
 
-      - name: Run nimbus-eth1 tests (Macos)
-        if: runner.os == 'Macos'
-        run: |
-          export ZERO_AR_DATE=1 # avoid timestamps in binaries
-          DEFAULT_MAKE_FLAGS="-j${ncpu} ENABLE_EVMC=${ENABLE_EVMC}"
-          make ${DEFAULT_MAKE_FLAGS}
-          build/nimbus --help
-          # "-static" option will not work for osx unless static system libraries are provided
-          # pushd vendor/nimbus-eth2
-          # env NIMBUSEL_BINARY=../../build/nimbus NIMBUSEL_GENESIS=scripts/nimbusel_genesis.json \
-          # ./scripts/launch_local_testnet.sh --nodes=3 --stop-at-epoch=7 \
-          # --disable-htop --reuse-binaries --run-nimbus-el --dl-eth2 --verbose --kill-old-processes
-          # popd
-          make ${DEFAULT_MAKE_FLAGS} test
-
+      # - name: Run nimbus-eth1 tests (Macos)
+      #   if: runner.os == 'Macos'
+      #   run: |
+      #     export ZERO_AR_DATE=1 # avoid timestamps in binaries
+      #     ENABLE_EVMC=${ENABLE_EVMC} nimble test -y
+      #     build/nimbus --help
+      #     # "-static" option will not work for osx unless static system libraries are provided
+      #     # pushd vendor/nimbus-eth2
+      #     # env NIMBUSEL_BINARY=../../build/nimbus NIMBUSEL_GENESIS=scripts/nimbusel_genesis.json \
+      #     # ./scripts/launch_local_testnet.sh --nodes=3 --stop-at-epoch=7 \
+      #     # --disable-htop --reuse-binaries --run-nimbus-el --dl-eth2 --verbose --kill-old-processes
+      #     # popd
+      #     make ${DEFAULT_MAKE_FLAGS} test
